name: Response Time CI
on:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
    types: [response_time]
  workflow_dispatch:

jobs:
  release:
    name: Check status
    runs-on: ubuntu-latest
    steps:
      - uses: upptime/response-time-action@master
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
